image: gitpod/workspace-mysql
ports:
  - port: 8080
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
  - port: 33060
    onOpen: ignore
  - port: 6379
    onOpen: ignore
tasks:
  - init: >
      composer install &&
      php -r 'file_exists(".env") || copy(".env.example", ".env");' &&
      php artisan key:generate --ansi &&
      mysql -u root -e "CREATE DATABASE laravel" &&
      php artisan migrate
    command: php artisan serve --host 0.0.0.0 --port 8080
